#!/bin/sh
#
# Script for filehandling module
#

case "$1" in
  start)
 	echo $'Loading module...\n'
	insmod /bin/testFile.ko
	echo $'Creating device file...\n'
	sleep 1
	mknod /dev/testFile c 247 0
	cat /var/log/messages | tail -6
	echo $'\nTry on of the following params:\n'
	echo $'  on - to switch the led on'
	echo $'  off - to switch the led off'
	echo $'  state - to get te actual LED state\n'
	;;
  stop)
	echo -n $'Stopping module...\n'
	rmmod testFile
	echo $'Removing device file...\n'
	rm /dev/testFile
	echo $'Succesfully stopped the module and removed the device file.'
	;;
  info)
	cat /var/log/messages | tail -20
	;;

  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|info|on|off|state}"
	exit 1
esac

exit $?
